# Generated by Django 4.2 on 2025-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeawaterFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(db_index=True, help_text='Latitude coordinate, e.g., 28.743')),
                ('longitude', models.FloatField(db_index=True, help_text='Longitude coordinate, e.g., -80.837')),
                ('salinity', models.FloatField(blank=True, help_text='Salinity measurement in PSU', null=True)),
                ('silicate', models.FloatField(blank=True, help_text='Silicate concentration in μmol/L', null=True)),
                ('phosphate', models.FloatField(blank=True, help_text='Phosphate concentration in μmol/L', null=True)),
                ('nitrate', models.FloatField(blank=True, help_text='Nitrate concentration in μmol/L', null=True)),
                ('iron', models.FloatField(blank=True, help_text='Iron concentration in μmol/L', null=True)),
                ('ph', models.FloatField(blank=True, help_text='pH value', null=True)),
                ('dissolved_oxygen', models.FloatField(blank=True, help_text='Dissolved molecular oxygen in μmol/kg', null=True)),
                ('ocean_temperature', models.FloatField(blank=True, help_text='Ocean temperature in °C', null=True)),
                ('seawater_direction', models.FloatField(blank=True, help_text='Sea water direction in degrees', null=True)),
                ('seawater_speed', models.FloatField(blank=True, help_text='Seawater speed in m/s', null=True)),
                ('primary_productivity', models.FloatField(blank=True, help_text='Primary productivity in mg C/m³/day', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['latitude', 'longitude'],
            },
        ),
        migrations.AddIndex(
            model_name='seawaterfactor',
            index=models.Index(fields=['latitude', 'longitude'], name='seawater_fa_latitud_aac55e_idx'),
        ),
        migrations.AddIndex(
            model_name='seawaterfactor',
            index=models.Index(fields=['ocean_temperature'], name='seawater_fa_ocean_t_5363d1_idx'),
        ),
        migrations.AddIndex(
            model_name='seawaterfactor',
            index=models.Index(fields=['salinity'], name='seawater_fa_salinit_1dfacd_idx'),
        ),
        migrations.AddIndex(
            model_name='seawaterfactor',
            index=models.Index(fields=['ph'], name='seawater_fa_ph_a1f2d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seawaterfactor',
            unique_together={('latitude', 'longitude')},
        ),
    ]
