# Generated by Django 4.2 on 2025-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(db_index=True, help_text='Latitude coordinate, e.g., 28.743')),
                ('longitude', models.FloatField(db_index=True, help_text='Longitude coordinate, e.g., -80.837')),
                ('average_organic_carbon', models.FloatField(blank=True, help_text='Average organic carbon content (%)', null=True)),
                ('organic_carbon_upper_depth', models.IntegerField(blank=True, help_text='Upper depth for organic carbon measurement (cm)', null=True)),
                ('organic_carbon_lower_depth', models.IntegerField(blank=True, help_text='Lower depth for organic carbon measurement (cm)', null=True)),
                ('average_total_carbon', models.FloatField(blank=True, help_text='Average total carbon content (%)', null=True)),
                ('total_carbon_upper_depth', models.IntegerField(blank=True, help_text='Upper depth for total carbon measurement (cm)', null=True)),
                ('total_carbon_lower_depth', models.IntegerField(blank=True, help_text='Lower depth for total carbon measurement (cm)', null=True)),
                ('average_organic_matter', models.FloatField(blank=True, help_text='Average organic matter content (%)', null=True)),
                ('organic_matter_upper_depth', models.IntegerField(blank=True, help_text='Upper depth for organic matter measurement (cm)', null=True)),
                ('organic_matter_lower_depth', models.IntegerField(blank=True, help_text='Lower depth for organic matter measurement (cm)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['latitude', 'longitude'],
            },
        ),
        migrations.AddIndex(
            model_name='soilfactor',
            index=models.Index(fields=['latitude', 'longitude'], name='soil_factor_latitud_59a02f_idx'),
        ),
        migrations.AddIndex(
            model_name='soilfactor',
            index=models.Index(fields=['average_organic_carbon'], name='soil_factor_average_04705c_idx'),
        ),
        migrations.AddIndex(
            model_name='soilfactor',
            index=models.Index(fields=['average_total_carbon'], name='soil_factor_average_f6f9be_idx'),
        ),
        migrations.AddIndex(
            model_name='soilfactor',
            index=models.Index(fields=['average_organic_matter'], name='soil_factor_average_e015f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='soilfactor',
            unique_together={('latitude', 'longitude')},
        ),
    ]
