# Generated by Django 4.2 on 2025-03-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('DB', 'Database Content'), ('BUG', 'Bug Report'), ('FEATURE', 'Feature Request'), ('RECORD', 'Record Submission'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
