# Generated by Django 4.2 on 2025-03-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('virus_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Virus ID')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('multi', models.FloatField(verbose_name='Multiplicity')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('quality', models.CharField(max_length=50, verbose_name='Quality')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('taxonomy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxonomy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
            ],
            options={
                'verbose_name': 'Virus',
                'verbose_name_plural': 'Viruses',
                'ordering': ['virus_id'],
            },
        ),
    ]
