# Generated by Django 4.2 on 2025-03-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amplicon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(db_index=True, help_text='Run ID, e.g., SRR15928122', max_length=100, unique=True)),
                ('assay_type', models.CharField(blank=True, help_text='Sequencing assay type, e.g., AMPLICON', max_length=100, null=True)),
                ('bioproject', models.CharField(blank=True, db_index=True, help_text='Bioproject ID, e.g., PRJNA764039', max_length=100, null=True)),
                ('habitat', models.CharField(blank=True, help_text='Habitat type, e.g., Mangrove', max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, help_text='Latitude, e.g., 16.3862 S', max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, help_text='Longitude, e.g., 145.5638 E', max_length=100, null=True)),
                ('geo_location', models.CharField(blank=True, help_text='Geographic location, e.g., Australia: GBR', max_length=500, null=True)),
                ('collection_date', models.CharField(blank=True, help_text='Collection date', max_length=100, null=True)),
                ('host', models.CharField(blank=True, db_index=True, help_text='Host, e.g., coral', max_length=500, null=True)),
                ('sample_isolated', models.CharField(blank=True, help_text='Sample isolated from, e.g., coral', max_length=500, null=True)),
                ('bases', models.BigIntegerField(blank=True, help_text='Number of bases', null=True)),
                ('biosample', models.CharField(blank=True, db_index=True, help_text='Biosample ID, e.g., SAMN21467046', max_length=100, null=True)),
                ('layout', models.CharField(blank=True, help_text='Sequencing layout, e.g., PAIRED', max_length=50, null=True)),
                ('instrument', models.CharField(blank=True, help_text='Sequencing instrument, e.g., Illumina MiSeq', max_length=200, null=True)),
                ('library_source', models.CharField(blank=True, help_text='Library source, e.g., GENOMIC', max_length=100, null=True)),
                ('amplicon_type', models.CharField(blank=True, help_text='Amplicon type, e.g., 16S', max_length=50, null=True)),
                ('reference', models.URLField(blank=True, help_text='Reference link, e.g., https://www.ncbi.nlm.nih.gov/sra/SRR15928122', max_length=500, null=True)),
            ],
            options={
                'ordering': ['run', 'geo_location', 'host', 'collection_date'],
            },
        ),
        migrations.AddIndex(
            model_name='amplicon',
            index=models.Index(fields=['run', 'geo_location', 'host', 'collection_date'], name='amplicon_am_run_7a6a46_idx'),
        ),
        migrations.AddIndex(
            model_name='amplicon',
            index=models.Index(fields=['bioproject'], name='amplicon_am_bioproj_1a2cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='amplicon',
            index=models.Index(fields=['biosample'], name='amplicon_am_biosamp_1c2db4_idx'),
        ),
        migrations.AddIndex(
            model_name='amplicon',
            index=models.Index(fields=['amplicon_type'], name='amplicon_am_amplico_45b2c2_idx'),
        ),
    ]
