# Generated by Django 4.2 on 2025-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taxonomy', models.TextField(db_index=True, help_text='Full taxonomic lineage, e.g., d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria')),
                ('function', models.CharField(db_index=True, help_text='Functional process, e.g., methanotrophy, nitrification', max_length=200)),
                ('function_type', models.CharField(db_index=True, help_text='Function type/category, e.g., C, N', max_length=50)),
                ('habitat', models.CharField(db_index=True, help_text='Habitat type, e.g., mangrove', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['taxonomy', 'function'],
            },
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['taxonomy'], name='record_reco_taxonom_ceaa37_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['function'], name='record_reco_functio_87444f_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['function_type'], name='record_reco_functio_20dd44_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['habitat'], name='record_reco_habitat_9705ab_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['function_type', 'habitat'], name='record_reco_functio_d0fada_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['function', 'habitat'], name='record_reco_functio_a89d43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('taxonomy', 'function', 'habitat')},
        ),
    ]
