# Generated by Django 4.2 on 2025-03-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(help_text='Gene identifier(s), can be multiple IDs separated by commas', max_length=1000)),
                ('preferred_name', models.CharField(blank=True, help_text='Preferred gene name if available', max_length=100, null=True)),
                ('cog_category', models.CharField(blank=True, help_text='COG functional category, e.g., F, T, S', max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Functional description of the gene', null=True)),
                ('cazy', models.CharField(blank=True, help_text='CAZy classification if available', max_length=100, null=True)),
                ('source', models.CharField(db_index=True, help_text='Source identifier, e.g., SRR25010671', max_length=100)),
                ('sequence', models.TextField(help_text='Amino acid sequence of the gene')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source', 'gene_id'],
            },
        ),
        migrations.AddIndex(
            model_name='gene',
            index=models.Index(fields=['gene_id'], name='gene_gene_gene_id_63897b_idx'),
        ),
        migrations.AddIndex(
            model_name='gene',
            index=models.Index(fields=['preferred_name'], name='gene_gene_preferr_fc33fe_idx'),
        ),
        migrations.AddIndex(
            model_name='gene',
            index=models.Index(fields=['cog_category'], name='gene_gene_cog_cat_228691_idx'),
        ),
        migrations.AddIndex(
            model_name='gene',
            index=models.Index(fields=['source'], name='gene_gene_source_2379eb_idx'),
        ),
    ]
