# Generated by Django 4.2 on 2025-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metagenome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, help_text='Run identifier, e.g., SRR25010643', max_length=100, unique=True)),
                ('bioproject', models.CharField(blank=True, db_index=True, help_text='BioProject identifier, e.g., PRJNA985394', max_length=100, null=True)),
                ('strategy', models.CharField(blank=True, help_text='Sequencing strategy, e.g., WGS', max_length=50, null=True)),
                ('library_source', models.CharField(blank=True, help_text='Library source, e.g., METAGENOMIC', max_length=50, null=True)),
                ('bases', models.BigIntegerField(blank=True, help_text='Number of bases sequenced', null=True)),
                ('instrument', models.CharField(blank=True, help_text='Sequencing instrument, e.g., Illumina NovaSeq 6000', max_length=200, null=True)),
                ('layout', models.CharField(blank=True, help_text='Sequencing layout, e.g., PAIRED', max_length=50, null=True)),
                ('habitat', models.CharField(blank=True, db_index=True, help_text='Habitat type, e.g., Seagrass', max_length=200, null=True)),
                ('collection_date', models.CharField(blank=True, help_text='Collection date, e.g., 2021/6/1', max_length=100, null=True)),
                ('sample_isolated', models.CharField(blank=True, help_text='Sample isolation source, e.g., sediment', max_length=200, null=True)),
                ('host', models.CharField(blank=True, db_index=True, help_text='Host organism, e.g., Zostera marina', max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, help_text='Latitude, e.g., 37.21N', max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, help_text='Longitude, e.g., 122.62E', max_length=50, null=True)),
                ('geo_location', models.CharField(blank=True, help_text='Geographic location, e.g., China:Shandong', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['run_id'],
            },
        ),
        migrations.AddIndex(
            model_name='metagenome',
            index=models.Index(fields=['run_id'], name='metagenome__run_id_4d9b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='metagenome',
            index=models.Index(fields=['bioproject'], name='metagenome__bioproj_2f4e01_idx'),
        ),
        migrations.AddIndex(
            model_name='metagenome',
            index=models.Index(fields=['habitat'], name='metagenome__habitat_4e8a60_idx'),
        ),
        migrations.AddIndex(
            model_name='metagenome',
            index=models.Index(fields=['host'], name='metagenome__host_284ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='metagenome',
            index=models.Index(fields=['geo_location'], name='metagenome__geo_loc_ded838_idx'),
        ),
    ]
