# Generated by Django 4.2 on 2025-03-20 12:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy', models.TextField(db_index=True, help_text='Complete GTDB taxonomy string', unique=True)),
                ('domain', models.CharField(db_index=True, help_text='Domain classification (d__)', max_length=100)),
                ('phylum', models.CharField(db_index=True, help_text='Phylum classification (p__)', max_length=100)),
                ('class_name', models.CharField(db_index=True, help_text='Class classification (c__)', max_length=100)),
                ('order', models.CharField(db_index=True, help_text='Order classification (o__)', max_length=100)),
                ('family', models.CharField(db_index=True, help_text='Family classification (f__)', max_length=100)),
                ('genus', models.CharField(db_index=True, help_text='Genus classification (g__)', max_length=100)),
                ('species', models.CharField(blank=True, db_index=True, help_text='Species classification (s__), if available', max_length=100, null=True)),
                ('functions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='List of metabolic or functional capabilities', size=None)),
                ('habitats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='List of habitats where the microbe is found', size=None)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), help_text='List of source identifiers (e.g., SRR numbers)', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain', 'phylum', 'genus', 'species'],
            },
        ),
        migrations.AddIndex(
            model_name='microbe',
            index=models.Index(fields=['taxonomy'], name='microbe_mic_taxonom_a4ba0e_idx'),
        ),
        migrations.AddIndex(
            model_name='microbe',
            index=models.Index(fields=['domain'], name='microbe_mic_domain_3b4cef_idx'),
        ),
        migrations.AddIndex(
            model_name='microbe',
            index=models.Index(fields=['phylum'], name='microbe_mic_phylum_f3ded3_idx'),
        ),
        migrations.AddIndex(
            model_name='microbe',
            index=models.Index(fields=['genus', 'species'], name='microbe_mic_genus_4a446c_idx'),
        ),
    ]
