# Generated by Django 4.2 on 2025-03-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbe',
            name='class_name',
            field=models.CharField(db_index=True, help_text='Class classification (c__)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microbe',
            name='domain',
            field=models.CharField(db_index=True, help_text='Domain classification (d__)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microbe',
            name='family',
            field=models.CharField(db_index=True, help_text='Family classification (f__)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microbe',
            name='genus',
            field=models.CharField(db_index=True, help_text='Genus classification (g__)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microbe',
            name='order',
            field=models.CharField(db_index=True, help_text='Order classification (o__)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microbe',
            name='phylum',
            field=models.CharField(db_index=True, help_text='Phylum classification (p__)', max_length=100, null=True),
        ),
    ]
